### ISSUE TITLE
Possibility to track scroll status within element other than body/window

### ISSUE THREAD

**Issue by intelligence** [Integreat/react-sticky-headroom#16]
Hey again.

Sorry to litter your great project with feature requests, but I really enjoyed your implementation in favor of `react-headroom` so maybe some additional features might bring more traction for your project.

Anyhow, I found myself needing to disable `overflow` on `body`. I've wrapped my site in a `div` that has `overflow: scroll` instead. Would be nice to provide a `parent` element as `react-headroom` lets you do!

**Comment by Schedulaar** [comment]
Closed by https://github.com/Integreat/react-sticky-headroom/pull/19
